/**
 * Upload all V2 gallery images to Supabase Storage and update DB galeria arrays.
 *
 * Usage: npx tsx scripts/upload-v2-gallery.ts
 *
 * Reads upload-manifest.json (generated by the migration tooling) which maps
 * each product to its local gallery files. Uploads each file to the
 * `product-images` bucket under `{productId}/{filename}`, then writes the
 * public URLs back to the `galeria` column in the `products` table.
 *
 * Already-uploaded files (same path) are skipped automatically.
 */

import { createClient } from "@supabase/supabase-js";
import * as fs from "fs";
import * as path from "path";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

interface ManifestFile {
  filename: string;
  local_path: string;
  size_kb: number;
}

interface ManifestEntry {
  id: string;
  foto_principal: string;
  galeria: ManifestFile[];
}

const BUCKET = "product-images";
const CONCURRENCY = 3; // parallel uploads per product

async function uploadFile(
  productId: string,
  file: ManifestFile
): Promise<string | null> {
  const storagePath = `${productId}/${file.filename}`;
  const ext = path.extname(file.filename).toLowerCase();
  const contentType =
    ext === ".png"
      ? "image/png"
      : ext === ".webp"
        ? "image/webp"
        : "image/jpeg";

  const fileBuffer = fs.readFileSync(file.local_path);

  const { error } = await supabase.storage.from(BUCKET).upload(storagePath, fileBuffer, {
    contentType,
    cacheControl: "31536000",
    upsert: false, // skip if already exists
  });

  if (error) {
    if (error.message?.includes("already exists") || error.message?.includes("Duplicate")) {
      // Already uploaded — just get the URL
    } else {
      console.error(`  FAIL ${file.filename}: ${error.message}`);
      return null;
    }
  }

  const {
    data: { publicUrl },
  } = supabase.storage.from(BUCKET).getPublicUrl(storagePath);
  return publicUrl;
}

async function processProduct(entry: ManifestEntry): Promise<void> {
  console.log(`\n📦 ${entry.id} — ${entry.galeria.length} files`);

  const urls: string[] = [];
  let fotoUrl: string | null = null;

  // Upload in batches of CONCURRENCY
  for (let i = 0; i < entry.galeria.length; i += CONCURRENCY) {
    const batch = entry.galeria.slice(i, i + CONCURRENCY);
    const results = await Promise.all(
      batch.map((file) => uploadFile(entry.id, file))
    );
    for (let j = 0; j < results.length; j++) {
      const url = results[j];
      if (url) {
        urls.push(url);
        if (batch[j].filename === entry.foto_principal) {
          fotoUrl = url;
        }
      }
    }
    process.stdout.write(
      `  uploaded ${Math.min(i + CONCURRENCY, entry.galeria.length)}/${entry.galeria.length}\r`
    );
  }

  console.log(`  ✅ ${urls.length} URLs ready`);

  if (urls.length === 0) return;

  // Update DB: set galeria and optionally foto_principal
  const update: Record<string, unknown> = { galeria: urls };
  if (fotoUrl) {
    update.foto_principal = fotoUrl;
  }

  const { error: dbErr } = await supabase
    .from("products")
    .update(update)
    .eq("id", entry.id);

  if (dbErr) {
    console.error(`  DB ERROR for ${entry.id}: ${dbErr.message}`);
  } else {
    console.log(
      `  DB updated: galeria=${urls.length}${fotoUrl ? " + foto_principal" : ""}`
    );
  }
}

async function main() {
  const manifestPath = path.join(__dirname, "upload-manifest.json");
  const manifest: ManifestEntry[] = JSON.parse(
    fs.readFileSync(manifestPath, "utf-8")
  );

  console.log(`🚀 Uploading gallery images for ${manifest.length} products`);
  console.log(`   Total files: ${manifest.reduce((s, e) => s + e.galeria.length, 0)}`);

  let totalUploaded = 0;
  for (const entry of manifest) {
    await processProduct(entry);
    totalUploaded += entry.galeria.length;
  }

  console.log(`\n🎉 Done! Processed ${totalUploaded} files across ${manifest.length} products.`);
}

main().catch(console.error);
